sonar.projectKey=jdgut_curso-cicd-entrega-final-bd
sonar.organization=jdgut
sonar.sources=.
sonar.inclusions=Dockerfile,init/**/*.sql,.github/workflows/*.yml
sonar.exclusions=**/.git/**,**/.venv/**,**/venv/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.coverage.exclusions=**/*
sonar.tests=
sonar.cpd.exclusions=**/*